### ISSUE TITLE
Concept, or 1.0.0 TODO

### ISSUE THREAD

**Issue by dy** [web-being/web-being.github.io#1]
So far it is just a stub with form.
@bvarba after you join I suggest discussing/brainstorming ideas and the concept more precisely, and making use out of the endeavour.

Things we need so far:
- [ ] portfolio of sites, to show and prove that we are able to do sites within reasonable resources. That is going to be a social proof and example for new clients.
- [ ] single portfolio item page, to show how we approach a project. We have to collect the requirements first.
  - [ ] Credits with roles
  - [ ] Price paid
  - [ ] Time spent

Ideas:
- Show progress of collected money so far, like kickstarter? That progress would reflect how much we affected the "world", in terms of other people’s gratitude.

**Comment by bvarba** [comment]
Websites done:
https://lerouge.ca/
http://mojitomusic.ca/
http://www.lidiavarbanova.ca/
http://www.melissabreault.ca/wp/
http://mirca.ca

**Comment by bvarba** [comment]
I was reading at the Pay-what you want article and they talk about how this authur made his ebook for 1$+. So pay anything over 1$. 
Lt's do something like this:
say 300+ or some base+
or maybe per feature or type of website

**Comment by bvarba** [comment]
I got a potential client already :)

An artist, his name is Myles, friend of Melissa's, he had started this website:
https://montrealartexhibited.wordpress.com/

Looks like he want's to make it better or has some ideas, i don;t know yet
 I'll talk with him to find out more.
And he has said explicitly to Melissa that he wants to pay.

It could be a good match.
Would you be interested to take something like that?

I'll talk with him and find out more and give you info. 
Let's agree on some sort of a PWYW model to get this thing starting.

**Comment by bvarba** [comment]
For the site sections keep it simple one page with a menu on top with anchors to the sections.

About
How we do it?
short paragraph or diagram or something visual to describe the process.

We work in quick agile development environment. Which means that you will see your site getting build and you will be meeting with us from time to time to get feedback and make sure the site is going in the direction that fits your vision. 
/_We first meet or speak with you on skype or something... hmm which makes me think is it Montreal mainly?
I'd start with people that can meet. I find it's easier. If it's people we trust than can meet at my place or something otherwise we can meet at a cafe._/
We meet with you first to find out what is your vision and how we can help it come to life.
Then we come back with you with a proposal and then we start the process iteration of one or two weeks. where we meet/online talk with you and agree on features and design that we would have for the next meeting. it all a circular process where the design and features get implemented untill the site is online.
We don't come up with content, it would have to come from you. We can inspire you to come up with some if you can't.

/_what about hosting? Templates?  all these expenses, etc.. let's talk about it_/

**Comment by dy** [comment]
> per feature

I like that, that is a good way to communicate, how do we make it work with pwyw model? We def have to track list of them, to report to client. Mb show average price of that job and let client decide how much to pay for it? To make it fair.

**Comment by bvarba** [comment]
What is the legal aspect of a PWYW model? Taxes? Lol

**Comment by dy** [comment]
Same as usual invoice, client just sets the price
